import { defineField, defineType } from 'sanity';

export const property = defineType({
  name: 'property',
  title: 'Property',
  type: 'document',
  groups: [
    { name: 'details', title: 'Details' },
    { name: 'media', title: 'Media' },
    { name: 'meta', title: 'Meta' },
  ],
  fields: [
    defineField({ name: 'title', title: 'Title', type: 'string', validation: (r) => r.required(), group: 'details' }),
    defineField({
      name: 'slug',
      title: 'Slug (URL)',
      type: 'slug',
      options: { source: 'title', maxLength: 96 },
      validation: (r) => r.required(),
      group: 'details',
    }),
    defineField({ name: 'community', title: 'Community', type: 'string', validation: (r) => r.required(), group: 'details' }),
    defineField({ name: 'subCommunity', title: 'Sub-community', type: 'string', group: 'details' }),
    defineField({
      name: 'type',
      title: 'Property Type',
      type: 'string',
      options: { list: ['Apartment', 'Penthouse', 'Villa', 'Townhouse', 'Mansion', 'Plot'] },
      validation: (r) => r.required(),
      group: 'details',
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      options: { list: ['For Sale', 'For Rent'] },
      validation: (r) => r.required(),
      group: 'details',
    }),
    defineField({ name: 'priceAED', title: 'Price (AED)', type: 'number', validation: (r) => r.required().positive(), group: 'details' }),
    defineField({
      name: 'rentPeriod',
      title: 'Rent Period',
      type: 'string',
      options: { list: ['yearly', 'monthly'] },
      hidden: ({ document }) => document?.status !== 'For Rent',
      group: 'details',
    }),
    defineField({ name: 'beds', title: 'Bedrooms', type: 'number', validation: (r) => r.required().min(0), group: 'details' }),
    defineField({ name: 'baths', title: 'Bathrooms', type: 'number', validation: (r) => r.required().min(0), group: 'details' }),
    defineField({ name: 'parking', title: 'Parking Spaces', type: 'number', group: 'details' }),
    defineField({ name: 'sizeSqft', title: 'Size (sqft)', type: 'number', validation: (r) => r.required().positive(), group: 'details' }),
    defineField({ name: 'plotSqft', title: 'Plot Size (sqft)', type: 'number', group: 'details' }),
    defineField({ name: 'developer', title: 'Developer', type: 'string', group: 'details' }),
    defineField({
      name: 'view',
      title: 'View',
      type: 'string',
      description: 'e.g. Community, Sea View, Golf Course, Skyline',
      group: 'details',
    }),
    defineField({
      name: 'availableFrom',
      title: 'Available / Vacant',
      type: 'string',
      description: 'e.g. "Immediately", "Apr 2027", "On Handover"',
      group: 'details',
    }),
    defineField({
      name: 'furnishing',
      title: 'Furnishing',
      type: 'string',
      options: { list: ['Furnished', 'Unfurnished', 'Partly Furnished'] },
      group: 'details',
    }),
    defineField({
      name: 'completion',
      title: 'Completion',
      type: 'string',
      options: { list: ['Ready', 'Off-Plan'] },
      validation: (r) => r.required(),
      group: 'details',
    }),
    defineField({ name: 'images', title: 'Images', type: 'array', of: [{ type: 'image', options: { hotspot: true } }], group: 'media' }),
    defineField({
      name: 'location',
      title: 'Map Location',
      type: 'geopoint',
      description: 'Exact pin for this property. Leave empty to fall back to the community’s location.',
      group: 'details',
    }),
    defineField({ name: 'description', title: 'Description', type: 'text', rows: 5, group: 'details' }),
    defineField({ name: 'amenities', title: 'Amenities', type: 'array', of: [{ type: 'string' }], group: 'details' }),
    defineField({
      name: 'agent',
      title: 'Listing Agent',
      type: 'reference',
      to: [{ type: 'agent' }],
      group: 'meta',
    }),
    defineField({
      name: 'tags',
      title: 'Collection Tags',
      type: 'array',
      of: [{ type: 'string' }],
      options: { list: ['Exclusive', 'New', 'Waterfront', 'Sky Villa', 'Branded Residence'] },
      group: 'meta',
    }),
    defineField({ name: 'featured', title: 'Featured on Homepage', type: 'boolean', initialValue: false, group: 'meta' }),
    defineField({
      name: 'showInActivity',
      title: 'Show in "Live Portfolio Activity"',
      type: 'boolean',
      initialValue: false,
      description: 'Shows this listing in the scrolling activity feed on the homepage.',
      group: 'meta',
    }),
    defineField({
      name: 'activityLabel',
      title: 'Activity Label',
      type: 'string',
      options: { list: ['Just Listed', 'Price Updated', 'Under Offer', 'New Match', 'Reserved', 'Sold'] },
      hidden: ({ document }) => !document?.showInActivity,
      group: 'meta',
    }),
    defineField({ name: 'yearBuilt', title: 'Year Built', type: 'number', group: 'meta' }),
    defineField({ name: 'reference', title: 'Reference Number', type: 'string', group: 'meta' }),
    defineField({
      name: 'transactions',
      title: 'DLD Transactions History',
      type: 'array',
      description: 'Official DLD registered transactions. If left empty, verified community benchmark records will display automatically.',
      group: 'details',
      of: [
        {
          type: 'object',
          name: 'transaction',
          fields: [
            { name: 'date', title: 'Date (DD/MM/YYYY)', type: 'string' },
            { name: 'unitNumber', title: 'Unit Number / Ref', type: 'string' },
            { name: 'type', title: 'Type', type: 'string', options: { list: ['Primary', 'Resale', 'New Lease', 'Renewal'] }, initialValue: 'Resale' },
            { name: 'rooms', title: 'Rooms', type: 'number' },
            { name: 'procedure', title: 'Procedure', type: 'string', initialValue: 'Sales' },
            { name: 'areaSqm', title: 'Area (sqm)', type: 'number' },
            { name: 'priceAED', title: 'Price / Annual Rent (AED)', type: 'number' },
          ],
        },
      ],
    }),
  ],
  preview: {
    select: { title: 'title', subtitle: 'community', media: 'images.0' },
  },
});
