import { defineField, defineType } from 'sanity';

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  groups: [
    { name: 'hero', title: 'Homepage Hero' },
    { name: 'interstitial', title: 'Cinematic Video Section' },
    { name: 'contact', title: 'Contact Info' },
    { name: 'legal', title: 'Legal & Licensing' },
  ],
  fields: [
    defineField({
      name: 'heroVideo',
      title: 'Hero Video',
      type: 'file',
      options: { accept: 'video/mp4' },
      description: 'The full-screen video behind the homepage headline. Keep it under ~15MB and 30-40s long for fast loading (compress with HandBrake or similar before uploading).',
      group: 'hero',
    }),
    defineField({ name: 'heroPoster', title: 'Hero Poster Image', type: 'image', description: 'Shown while the video loads.', group: 'hero' }),
    defineField({
      name: 'heroVideoMobile',
      title: 'Hero Video (Mobile Crop)',
      type: 'file',
      options: { accept: 'video/mp4' },
      description: 'Optional. A portrait-cropped version of the hero video for phones: the wide desktop video shows only a narrow sliver when stretched full-height on a phone, so this lets you frame it properly. Falls back to the main hero video if left empty.',
      group: 'hero',
    }),
    defineField({
      name: 'heroPosterMobile',
      title: 'Hero Poster Image (Mobile Crop)',
      type: 'image',
      description: 'Optional. Poster shown while the mobile video loads. Falls back to the main hero poster if left empty.',
      group: 'hero',
    }),
    defineField({ name: 'heroKicker', title: 'Hero Kicker Text', type: 'string', initialValue: 'Dubai · International Realty', group: 'hero' }),
    defineField({ name: 'heroHeadlineLine1', title: 'Hero Headline - Line 1', type: 'string', initialValue: 'Extraordinary addresses,', group: 'hero' }),
    defineField({ name: 'heroHeadlineLine2', title: 'Hero Headline - Line 2', type: 'string', initialValue: 'for an extraordinary city.', group: 'hero' }),
    defineField({ name: 'heroSubtitle', title: 'Hero Subtitle', type: 'text', rows: 3, group: 'hero' }),
    defineField({
      name: 'interstitialVideo',
      title: 'Cinematic Section Video',
      type: 'file',
      options: { accept: 'video/mp4' },
      description: 'The second video, shown lower on the homepage between New Developments and Communities.',
      group: 'interstitial',
    }),
    defineField({ name: 'interstitialHeadline', title: 'Cinematic Section Headline', type: 'string', group: 'interstitial' }),
    defineField({ name: 'interstitialBody', title: 'Cinematic Section Body', type: 'text', rows: 3, group: 'interstitial' }),
    defineField({ name: 'contactPhone', title: 'Phone', type: 'string', group: 'contact' }),
    defineField({ name: 'contactEmail', title: 'Email', type: 'string', group: 'contact' }),
    defineField({ name: 'whatsappNumber', title: 'WhatsApp Number', type: 'string', description: 'Digits only, e.g. 971501234567', group: 'contact' }),
    defineField({ name: 'officeAddress', title: 'Office Address', type: 'string', group: 'contact' }),
    defineField({ name: 'legalCompanyName', title: 'Legal Company Name', type: 'string', description: 'As registered with DED, e.g. "S I A Luxe Real Estate LLC".', group: 'legal' }),
    defineField({ name: 'tradeLicenseNumber', title: 'Trade License Number', type: 'string', group: 'legal' }),
    defineField({ name: 'reraOrn', title: 'RERA ORN (Brokerage Registration Number)', type: 'string', group: 'legal' }),
  ],
  preview: {
    prepare: () => ({ title: 'Site Settings' }),
  },
});
